
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    'hero.title': 'Bengkel Keliling Terpercaya',
    'hero.title.v27': 'Bengkel Masa Depan Dalam Genggaman.',
    'hero.subtitle': 'Panggil mekanik profesional ke lokasi Anda kapan saja, dimana saja',
    'hero.cta': 'Mulai Sekarang',
    'landing.badge': '#1 Bengkel Panggilan Indonesia v27',
    'landing.why': 'MENGAPA OKE MEKANIK?',
    'landing.cta_title': 'SIAP UNTUK PERJALANAN MULUS?',
    'landing.cta_quote': '"Satu-satunya platform di mana teknologi bertemu dengan penguasaan mekanis."',
    'landing.be_partner': 'JADI MITRA',
    'role.customer.title': 'Saya Pelanggan',
    'role.customer.desc': 'Butuh bantuan mekanik? Panggil sekarang juga!',
    'role.customer.button': 'Panggil Mekanik',
    'role.customer.btn_start': 'MULAI SEBAGAI PELANGGAN',
    'role.mechanic.title': 'Saya Mekanik',
    'role.mechanic.desc': 'Bergabung sebagai mitra mekanik profesional',
    'role.mechanic.button': 'Daftar Mekanik',
    'role.mechanic.btn_start': 'MULAI SEBAGAI MITRA',
    'features.title': 'Mengapa Pilih Oke Mekanik?',
    'feature.location.title': 'Lokasi Real-time',
    'feature.location.desc': 'Lacak mekanik menuju lokasi Anda secara real-time',
    'feature.realtime.title': 'Respon Cepat',
    'feature.realtime.desc': 'Mekanik terdekat akan segera merespon panggilan Anda',
    'feature.rating.title': 'Mekanik Terpercaya',
    'feature.rating.desc': 'Semua mekanik telah diverifikasi dan memiliki rating tinggi',
    'feature.verified.title': 'Identitas Terverifikasi',
    'feature.verified.desc': 'Keamanan terjamin dengan verifikasi identitas lengkap',
    'cta.title': 'Siap Memulai?',
    'cta.subtitle': 'Bergabunglah dengan ribuan pengguna yang puas',
    'cta.customer': 'Mulai sebagai Pelanggan',
    'cta.mechanic': 'Mulai sebagai Mekanik',
    'nav.login': 'Masuk',
    'nav.register': 'Daftar',
    'stats.active_users': 'PENGGUNA AKTIF',
    'stats.mechanic_partners': 'MITRA MEKANIK',
    'stats.avg_rating': 'RATING LAYANAN',
    'stats.arrival_eta': 'ESTIMASI TIBA',
    'stats.repair_time': 'REPAIR TIME',
    'common.call_now': 'PANGGIL SEKARANG',
    'common.learn_more': 'PELAJARI LEBIH LANJUT',
    'common.retry': 'Coba Lagi',
    'error.load_failed': 'Gagal memuat data',
    'error.data_error': 'Terjadi kesalahan saat mengambil data.',
    'footer.services': 'Layanan',
    'footer.ecosystem': 'Ekosistem',
    'footer.ai_diag': 'AI Diagnostic',
    'footer.fleet': 'Fleet Management',
    'footer.emergency_hub': 'Emergency Hub',
    'footer.roadside': 'Roadside Assist',
    'footer.global_support': 'Global Support',
    'footer.privacy': 'Privacy Protocol',
    'footer.terms': 'Service Terms',
    'footer.ethics': 'Neural Ethics',
    'footer.panggil': 'Panggil Mekanik',
    'footer.servis': 'Servis Rutin',
    'footer.oli': 'Ganti Oli',
    'footer.emergency': 'Emergency 24/7',
    'footer.contact': 'Hubungi Kami',
    'footer.rights': '© 2024 OKE MEKANIK MASTERPIECE v27. ENGINEERED FOR EXCELLENCE.',
    'footer.tagline': 'Revolusi servis kendaraan masa depan. Profesional, transparan, dan instan langsung ke lokasi Anda.',
    'footer.location': 'Jakarta, Indonesia',
    'login.title': 'Masuk ke akun Anda',
    'login.role.label': 'Masuk sebagai',
    'login.role.placeholder': 'Pilih peran',
    'login.role.customer': 'Pelanggan',
    'login.role.mechanic': 'Mekanik',
    'login.button.loading': 'Memuat...',
    'login.button': 'MASUK SEKARANG',
    'login.no_account': 'Belum punya akun?',
    'login.register_link': 'Daftar sekarang',
    'login.success': 'Login berhasil!',
    'login.error': 'Email atau password salah',
    'login.email': 'Email',
    'login.email_placeholder': 'nama@email.com',
    'login.password': 'Password',
    'login.password_placeholder': '******',
    'booking.title': 'PESAN MEKANIK',
    'booking.subtitle': 'Lengkapi detail di bawah untuk mendapatkan bantuan profesional',
    'booking.step1.title': 'Lokasi & Masalah Kendaraan',
    'booking.step1.address': 'Alamat Lengkap',
    'booking.step1.address_placeholder': 'Masukkan alamat lengkap',
    'booking.step1.gps': 'GPS',
    'booking.step1.brand': 'Merk Kendaraan',
    'booking.step1.brand_placeholder': 'Pilih merk',
    'booking.step1.model': 'Model/Tipe',
    'booking.step1.model_placeholder': 'Avanza, Vario, dll',
    'booking.step1.year': 'Tahun',
    'booking.step1.year_placeholder': '2019',
    'booking.step1.plate': 'Plat Nomor',
    'booking.step1.plate_placeholder': 'B 1234 XYZ',
    'booking.step1.problem': 'Masalah Kendaraan',
    'booking.step1.problem_placeholder': 'Pilih masalah atau gunakan AI',
    'booking.step1.problem_desc_placeholder': 'Tuliskan gejala atau masalah kendaraan Anda (contoh: mesin mati mendadak, aki soak, rem bunyi...)',
    'booking.step1.emergency_btn': 'DARURAT - Panggil Sekarang',
    'booking.step1.emergency_desc': 'Untuk situasi darurat yang membutuhkan bantuan segera',
    'booking.step1.next': 'Lanjutkan ke Pemilihan Mekanik',
    'booking.step2.title': 'Pilih Mekanik',
    'booking.step2.emergency': 'DARURAT',
    'booking.step2.next': 'Lanjutkan ke Konfirmasi',
    'booking.step3.title': 'Konfirmasi Booking',
    'booking.step3.details': 'Detail Booking',
    'booking.step3.mechanic': 'Mekanik:',
    'booking.step3.location': 'Lokasi:',
    'booking.step3.vehicle': 'Kendaraan:',
    'booking.step3.problem': 'Masalah:',
    'booking.step3.cost': 'Estimasi Biaya:',
    'booking.step3.eta': 'ETA:',
    'booking.step3.btn_chat': 'Chat',
    'booking.step3.btn_phone': 'Telepon',
    'booking.step3.confirm': 'Konfirmasi Booking',
    'booking.step3.processing': 'Memproses...',
    'booking.back': 'Kembali',
    'booking.back_dashboard': 'Kembali ke Dashboard',
    'tracking.title': 'LACAK PESANAN',
    'tracking.map_title': 'LOKASI MEKANIK REAL-TIME',
    'tracking.user_loc': 'Lokasi Anda',
    'tracking.mech_loc': 'Mekanik Oke Mekanik',
    'tracking.status.otw': 'MEKANIK SEDANG MENUJU ANDA',
    'tracking.status.preparing': 'MEKANIK MENYIAPKAN PERALATAN',
    'tracking.status.arrived': 'MEKANIK TELAH TIBA',
    'tracking.status.working': 'PERBAIKAN SEDANG BERLANGSUNG',
    'tracking.status.completed': 'PERBAIKAN SELESAI',
    'tracking.status.pending': 'MENUNGGU KONFIRMASI',
    'tracking.eta': 'Estimasi tiba:',
    'tracking.progress_title': 'STATUS PEKERJAAN',
    'tracking.info_title': 'INFORMASI LAYANAN',
    'tracking.mech_prof': 'Mekanik Profesional',
    'tracking.verified': 'TERVERIFIKASI',
    'tracking.vehicle': 'Kendaraan',
    'tracking.problem': 'Masalah',
    'tracking.cost': 'Biaya Estimasi',
    'tracking.btn_chat': 'CHAT',
    'tracking.btn_phone': 'TELEPON',
    'tracking.job_done': 'PEKERJAAN SELESAI! 🎉',
    'tracking.job_done_desc': 'Kendaraan Anda telah selesai diperbaiki dan siap digunakan kembali.',
    'tracking.btn_payment': 'LANJUT KE PEMBAYARAN',
    'tracking.help_title': 'BUTUH BANTUAN DARURAT?',
    'tracking.help_desc': 'Jika terjadi kendala mendesak, hubungi pusat bantuan kami segera.',
    'tracking.btn_support': 'HUBUNGI SUPPORT',
    'tracking.total_cost': 'Total Biaya',
    'tracking.btn_pay_now': 'BAYAR SEKARANG',
    'tracking.btn_view_detail': 'LIHAT DETAIL',
    'tracking.footer.secure': 'TRANSAKSI AMAN & TERPROTEKSI',
    'tracking.footer.pickup': 'LOKASI PENJEMPUTAN:',
    'chat.sender.mechanic': 'MEKANIK',
    'chat.sender.customer': 'PELANGGAN',
    'chat.connected': 'Terhubung',
    'chat.no_messages': 'Belum ada pesan',
    'chat.input_placeholder': 'Ketik pesan masa depan...',
    'dashboard.customer.help_title': 'BUTUH BANTUAN?',
    'dashboard.customer.help_subtitle': 'Panggil mekanik profesional dalam hitungan detik. Layanan 24/7 di lokasi Anda.',
    'dashboard.customer.btn_call': 'PANGGIL SEKARANG',
    'dashboard.customer.btn_emergency': 'DARURAT',
    'dashboard.customer.active_service': 'Layanan Aktif',
    'dashboard.customer.heading_to_loc': 'Mekanik Sedang Menuju Lokasi',
    'dashboard.customer.vehicle': 'Kendaraan:',
    'dashboard.customer.problem': 'Masalah:',
    'dashboard.customer.btn_chat': 'Chat',
    'dashboard.customer.btn_track': 'Lacak Lokasi',
    'dashboard.customer.nearby_mech': 'MEKANIK TERDEKAT',
    'dashboard.customer.no_nearby': 'Tidak ada mekanik tersedia saat ini',
    'dashboard.customer.btn_select': 'Pilih',
    'dashboard.customer.history': 'Riwayat Layanan',
    'dashboard.customer.no_history': 'Belum ada riwayat layanan',
    'dashboard.customer.btn_review': 'Beri Ulasan',
    'dashboard.customer.review_title': 'BERI ULASAN',
    'dashboard.customer.review_desc': 'Bagaimana pengalaman Anda dengan layanan ini?',
    'dashboard.customer.review_label': 'Komentar Anda',
    'dashboard.customer.review_placeholder': 'Ceritakan pengalaman Anda...',
    'dashboard.customer.btn_cancel': 'Batal',
    'dashboard.customer.btn_submit': 'Kirim Ulasan',
    'dashboard.customer.submitting': 'Mengirim...',
    'dashboard.customer.status_completed': 'Selesai',
    'register.title': 'DAFTAR OKE MEKANIK',
    'register.subtitle': 'Mulai perjalanan masa depan Anda bersama kami',
    'register.name': 'Nama Lengkap',
    'register.email': 'Email',
    'register.name_placeholder': 'Joko Susilo',
    'register.email_placeholder': 'nama@email.com',
    'register.password': 'Password',
    'register.password_placeholder': '******',
    'register.phone': 'Nomor Telepon',
    'register.phone_placeholder': '0812XXXXXXXX',
    'register.role.label': 'Daftar sebagai',
    'register.role.placeholder': 'Pilih peran',
    'register.role.customer': 'Pelanggan',
    'register.role.mechanic': 'Mekanik',
    'register.button.loading': 'Memuat...',
    'register.button': 'DAFTAR SEKARANG',
    'register.has_account': 'Sudah punya akun?',
    'register.login_link': 'Masuk di sini',
    'register.success': 'Pendaftaran berhasil!',
    'register.error': 'Pendaftaran gagal. Silakan coba lagi.',
    'dashboard.mechanic.online': 'Online',
    'dashboard.mechanic.offline': 'Offline',
    'dashboard.mechanic.orders_in': 'Pesanan Masuk',
    'dashboard.mechanic.active_job': 'Pekerjaan Aktif',
    'dashboard.mechanic.completed': 'Selesai',
    'dashboard.mechanic.rating': 'Rating',
    'dashboard.mechanic.current_job': 'Pekerjaan Saat Ini',
    'dashboard.mechanic.btn_chat': 'Chat',
    'dashboard.mechanic.btn_phone': 'Telepon',
    'dashboard.mechanic.btn_otw': 'Berangkat (OTW)',
    'dashboard.mechanic.btn_arrived': 'Tiba & Mulai Kerja',
    'dashboard.mechanic.btn_done': 'Selesai',
    'dashboard.mechanic.analytics': 'ANALISIS PENDAPATAN',
    'dashboard.mechanic.earnings_label': 'Total Pendapatan',
    'dashboard.mechanic.target_hit': 'Target Tercapai',
    'dashboard.mechanic.performance': 'TREN PERFORMA',
    'dashboard.mechanic.recent_reviews': 'Ulasan Terbaru',
    'dashboard.mechanic.no_reviews': 'Belum ada ulasan.',
    'dashboard.mechanic.orders_in_title': 'PESANAN MASUK',
    'dashboard.mechanic.btn_reject': 'Tolak',
    'dashboard.mechanic.btn_accept': 'Terima',
    'dashboard.mechanic.no_orders': 'Tidak ada pesanan masuk saat ini.',
    'mechanic.reg.title': 'PENDAFTARAN MITRA',
    'mechanic.reg.subtitle': 'Mulai karir masa depan Anda di Oke Mekanik',
    'mechanic.reg.step1_title': 'Informasi Keahlian',
    'mechanic.reg.speciality': 'Spesialisasi Utama',
    'mechanic.reg.spec_placeholder': 'Pilih Spesialisasi',
    'mechanic.reg.spec_car': 'Mobil Penumpang',
    'mechanic.reg.spec_motor': 'Sepeda Motor',
    'mechanic.reg.spec_truck': 'Kendaraan Berat / Truk',
    'mechanic.reg.spec_electric': 'Kendaraan Listrik',
    'mechanic.reg.experience': 'Pengalaman Kerja (Tahun)',
    'mechanic.reg.exp_placeholder': 'Contoh: 5',
    'mechanic.reg.step2_title': 'Informasi Kontak & Identitas',
    'mechanic.reg.phone': 'Nomor Telepon Aktif',
    'mechanic.reg.phone_placeholder': '0812...',
    'mechanic.reg.identity': 'Nomor KTP / NIK',
    'mechanic.reg.id_placeholder': '3201...',
    'mechanic.reg.bio': 'Biografi Singkat',
    'mechanic.reg.bio_placeholder': 'Ceritakan sedikit tentang keahlian Anda',
    'mechanic.reg.step3_title': 'Dokumen Pendukung',
    'mechanic.reg.upload_ktp': 'UNGGAH KTP',
    'mechanic.reg.upload_cert': 'UNGGAH SERTIFIKAT KEAHLIAN',
    'mechanic.reg.step4_title': 'Konfirmasi & Persetujuan',
    'mechanic.reg.terms_text': '"Dengan mendaftar, saya berkomitmen untuk menjaga standar kualitas tinggi Oke Mekanik, memberikan layanan profesional, dan menjunjung tinggi kejujuran dalam setiap pekerjaan."',
    'mechanic.reg.terms_check': 'Saya menyetujui seluruh syarat, ketentuan, dan kode etik mitra Oke Mekanik.',
    'mechanic.reg.btn_back': 'KEMBALI',
    'mechanic.reg.btn_next': 'LANJUT',
    'mechanic.reg.btn_finish': 'SELESAIKAN',
    'mechanic.reg.processing': 'MEMPROSES...',
    'mechanic.reg.secure_msg': 'Keamanan Data Terenkripsi SSL/TLS',
    'payment.title': 'PEMBAYARAN',
    'payment.secure_checkout': 'Secure Checkout',
    'payment.summary_title': 'RINGKASAN LAYANAN',
    'payment.label_problem': 'Masalah',
    'payment.label_vehicle': 'Kendaraan',
    'payment.label_order_id': 'ID Pesanan',
    'payment.total_cost': 'TOTAL BIAYA',
    'payment.methods_title': 'PILIH METODE PEMBAYARAN',
    'payment.methods_desc': 'Transaksi aman dan terenkripsi menggunakan sistem Oke Mekanik.',
    'payment.btn_pay': 'BAYAR SEKARANG',
    'payment.processing': 'MEMPROSES PEMBAYARAN...',
    'payment.processing_desc': 'Mohon jangan tutup halaman ini sampai konfirmasi selesai.',
    'payment.success_title': 'BERHASIL!',
    'payment.success_desc': 'Terima kasih telah mempercayai Oke Mekanik. Kendaraan Anda masa depan Anda.',
    'payment.btn_dashboard': 'DASHBOARD',
    'payment.btn_invoice': 'UNDUH INVOICE RESMI (PDF)',
    'payment.error_not_found': 'DATA TAGIHAN TIDAK DITEMUKAN',
    'payment.error_desc': 'Gagal memuat rincian pembayaran untuk pesanan ini.',
    'forgot.title': 'LUPA PASSWORD',
    'forgot.subtitle': 'Masukkan email Anda untuk menerima instruksi reset',
    'forgot.email': 'Email',
    'forgot.email_placeholder': 'email@contoh.com',
    'forgot.btn_send': 'KIRIM LINK RESET',
    'forgot.btn_back': 'KEMBALI KE LOGIN',
    'forgot.success': 'Instruksi reset password telah dikirim ke email Anda',
    'hero.title.v27.part1': 'Bengkel Masa Depan',
    'hero.title.v27.part2': 'Dalam Genggaman.',
    'nav.login_mobile': 'Masuk',
    'common.id': 'ID',
    'common.en': 'EN'
  },
  en: {
    'hero.title': 'Trusted Mobile Mechanic',
    'hero.title.v27': 'Future Workshop in Your Hands.',
    'hero.subtitle': 'Call professional mechanics to your location anytime, anywhere',
    'hero.cta': 'Start Now',
    'landing.badge': '#1 Mobile Mechanic Indonesia v27',
    'landing.why': 'WHY OKE MEKANIK?',
    'landing.cta_title': 'READY FOR A SMOOTH JOURNEY?',
    'landing.cta_quote': '"The only platform where technology meets mechanical mastery."',
    'landing.be_partner': 'BECOME A PARTNER',
    'role.customer.title': "I'm a Customer",
    'role.customer.desc': 'Need mechanic help? Call now!',
    'role.customer.button': 'Call Mechanic',
    'role.customer.btn_start': 'START AS CUSTOMER',
    'role.mechanic.title': "I'm a Mechanic",
    'role.mechanic.desc': 'Join as a professional mechanic partner',
    'role.mechanic.button': 'Register as Mechanic',
    'role.mechanic.btn_start': 'START AS PARTNER',
    'features.title': 'Why Choose Oke Mekanik?',
    'feature.location.title': 'Real-time Location',
    'feature.location.desc': 'Track mechanics heading to your location in real-time',
    'feature.realtime.title': 'Quick Response',
    'feature.realtime.desc': 'Nearest mechanics will respond to your call immediately',
    'feature.rating.title': 'Trusted Mechanics',
    'feature.rating.desc': 'All mechanics are verified and have high ratings',
    'feature.verified.title': 'Verified Identity',
    'feature.verified.desc': 'Security guaranteed with complete identity verification',
    'cta.title': 'Ready to Start?',
    'cta.subtitle': 'Join thousands of satisfied users',
    'cta.customer': 'Start as Customer',
    'cta.mechanic': 'Start as Mechanic',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'stats.active_users': 'ACTIVE USERS',
    'stats.mechanic_partners': 'MECHANIC PARTNERS',
    'stats.avg_rating': 'SERVICE RATING',
    'stats.arrival_eta': 'ARRIVAL ETA',
    'stats.repair_time': 'REPAIR TIME',
    'common.call_now': 'CALL NOW',
    'common.learn_more': 'LEARN MORE',
    'common.retry': 'Retry',
    'error.load_failed': 'Failed to load data',
    'error.data_error': 'An error occurred while fetching data.',
    'footer.services': 'Services',
    'footer.ecosystem': 'Ecosystem',
    'footer.ai_diag': 'AI Diagnostic',
    'footer.fleet': 'Fleet Management',
    'footer.emergency_hub': 'Emergency Hub',
    'footer.roadside': 'Roadside Assist',
    'footer.global_support': 'Global Support',
    'footer.privacy': 'Privacy Protocol',
    'footer.terms': 'Service Terms',
    'footer.ethics': 'Neural Ethics',
    'footer.panggil': 'Call Mechanic',
    'footer.servis': 'Routine Service',
    'footer.oli': 'Oil Change',
    'footer.emergency': 'Emergency 24/7',
    'footer.contact': 'Contact Us',
    'footer.rights': '© 2024 OKE MEKANIK MASTERPIECE v27. ENGINEERED FOR EXCELLENCE.',
    'footer.tagline': 'Future vehicle service revolution. Professional, transparent, and instant directly to your location.',
    'footer.location': 'Jakarta, Indonesia',
    'login.title': 'Login to your account',
    'login.role.label': 'Login as',
    'login.role.placeholder': 'Select role',
    'login.role.customer': 'Customer',
    'login.role.mechanic': 'Mechanic',
    'login.button.loading': 'Loading...',
    'login.button': 'LOGIN NOW',
    'login.no_account': "Don't have an account?",
    'login.register_link': 'Register now',
    'login.success': 'Login successful!',
    'login.error': 'Invalid email or password',
    'login.email': 'Email',
    'login.email_placeholder': 'name@email.com',
    'login.password': 'Password',
    'login.password_placeholder': '******',
    'booking.title': 'BOOK MECHANIC',
    'booking.subtitle': 'Complete the details below to get professional help',
    'booking.step1.title': 'Location & Vehicle Problem',
    'booking.step1.address': 'Full Address',
    'booking.step1.address_placeholder': 'Enter full address',
    'booking.step1.gps': 'GPS',
    'booking.step1.brand': 'Vehicle Brand',
    'booking.step1.brand_placeholder': 'Select brand',
    'booking.step1.model': 'Model/Type',
    'booking.step1.model_placeholder': 'Avanza, Vario, etc',
    'booking.step1.year': 'Year',
    'booking.step1.year_placeholder': '2019',
    'booking.step1.plate': 'License Plate',
    'booking.step1.plate_placeholder': 'B 1234 XYZ',
    'booking.step1.problem': 'Vehicle Problem',
    'booking.step1.problem_placeholder': 'Select problem or use AI',
    'booking.step1.problem_desc_placeholder': 'Write symptoms or vehicle problems (e.g., engine suddenly dies, weak battery, brake noise...)',
    'booking.step1.emergency_btn': 'EMERGENCY - Call Now',
    'booking.step1.emergency_desc': 'For emergency situations that need immediate help',
    'booking.step1.next': 'Continue to Mechanic Selection',
    'booking.step2.title': 'Select Mechanic',
    'booking.step2.emergency': 'EMERGENCY',
    'booking.step2.next': 'Continue to Confirmation',
    'booking.step3.title': 'Booking Confirmation',
    'booking.step3.details': 'Booking Details',
    'booking.step3.mechanic': 'Mechanic:',
    'booking.step3.location': 'Location:',
    'booking.step3.vehicle': 'Vehicle:',
    'booking.step3.problem': 'Problem:',
    'booking.step3.cost': 'Estimated Cost:',
    'booking.step3.eta': 'ETA:',
    'booking.step3.btn_chat': 'Chat',
    'booking.step3.btn_phone': 'Phone',
    'booking.step3.confirm': 'Confirm Booking',
    'booking.step3.processing': 'Processing...',
    'booking.back': 'Back',
    'booking.back_dashboard': 'Back to Dashboard',
    'tracking.title': 'TRACK ORDER',
    'tracking.map_title': 'REAL-TIME MECHANIC LOCATION',
    'tracking.user_loc': 'Your Location',
    'tracking.mech_loc': 'Oke Mekanik Mechanic',
    'tracking.status.otw': 'MECHANIC HEADING TO YOU',
    'tracking.status.preparing': 'MECHANIC PREPARING TOOLS',
    'tracking.status.arrived': 'MECHANIC HAS ARRIVED',
    'tracking.status.working': 'REPAIR IN PROGRESS',
    'tracking.status.completed': 'REPAIR COMPLETED',
    'tracking.status.pending': 'WAITING FOR CONFIRMATION',
    'tracking.eta': 'Estimated arrival:',
    'tracking.progress_title': 'WORK STATUS',
    'tracking.info_title': 'SERVICE INFORMATION',
    'tracking.mech_prof': 'Professional Mechanic',
    'tracking.verified': 'VERIFIED',
    'tracking.vehicle': 'Vehicle',
    'tracking.problem': 'Problem',
    'tracking.cost': 'Estimated Cost',
    'tracking.btn_chat': 'CHAT',
    'tracking.btn_phone': 'PHONE',
    'tracking.job_done': 'WORK COMPLETED! 🎉',
    'tracking.job_done_desc': 'Your vehicle has been repaired and is ready to use again.',
    'tracking.btn_payment': 'PROCEED TO PAYMENT',
    'tracking.help_title': 'NEED EMERGENCY HELP?',
    'tracking.help_desc': 'If there are urgent issues, contact our help center immediately.',
    'tracking.btn_support': 'CONTACT SUPPORT',
    'tracking.total_cost': 'Total Cost',
    'tracking.btn_pay_now': 'PAY NOW',
    'tracking.btn_view_detail': 'VIEW DETAIL',
    'tracking.footer.secure': 'SECURE & PROTECTED TRANSACTION',
    'tracking.footer.pickup': 'PICKUP LOCATION:',
    'chat.sender.mechanic': 'MECHANIC',
    'chat.sender.customer': 'CUSTOMER',
    'chat.connected': 'Connected',
    'chat.no_messages': 'No messages yet',
    'chat.input_placeholder': 'Type a message...',
    'dashboard.customer.help_title': 'NEED HELP?',
    'dashboard.customer.help_subtitle': 'Call professional mechanics in seconds. 24/7 service at your location.',
    'dashboard.customer.btn_call': 'CALL NOW',
    'dashboard.customer.btn_emergency': 'EMERGENCY',
    'dashboard.customer.active_service': 'Active Service',
    'dashboard.customer.heading_to_loc': 'Mechanic is Heading to Your Location',
    'dashboard.customer.vehicle': 'Vehicle:',
    'dashboard.customer.problem': 'Problem:',
    'dashboard.customer.btn_chat': 'Chat',
    'dashboard.customer.btn_track': 'Track Location',
    'dashboard.customer.nearby_mech': 'NEARBY MECHANICS',
    'dashboard.customer.no_nearby': 'No mechanics available at the moment',
    'dashboard.customer.btn_select': 'Select',
    'dashboard.customer.history': 'Service History',
    'dashboard.customer.no_history': 'No service history yet',
    'dashboard.customer.btn_review': 'Give Review',
    'dashboard.customer.review_title': 'GIVE REVIEW',
    'dashboard.customer.review_desc': 'How was your experience with this service?',
    'dashboard.customer.review_label': 'Your Comment',
    'dashboard.customer.review_placeholder': 'Tell us about your experience...',
    'dashboard.customer.btn_cancel': 'Cancel',
    'dashboard.customer.btn_submit': 'Submit Review',
    'dashboard.customer.submitting': 'Submitting...',
    'dashboard.customer.status_completed': 'Completed',
    'register.title': 'REGISTER OKE MEKANIK',
    'register.subtitle': 'Start your future journey with us',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.name_placeholder': 'John Doe',
    'register.email_placeholder': 'name@email.com',
    'register.password': 'Password',
    'register.password_placeholder': '******',
    'register.phone': 'Phone Number',
    'register.phone_placeholder': '0812XXXXXXXX',
    'register.role.label': 'Register as',
    'register.role.placeholder': 'Select role',
    'register.role.customer': 'Customer',
    'register.role.mechanic': 'Mechanic',
    'register.button.loading': 'Loading...',
    'register.button': 'REGISTER NOW',
    'register.has_account': 'Already have an account?',
    'register.login_link': 'Login here',
    'register.success': 'Registration successful!',
    'register.error': 'Registration failed. Please try again.',
    'dashboard.mechanic.online': 'Online',
    'dashboard.mechanic.offline': 'Offline',
    'dashboard.mechanic.orders_in': 'Incoming Orders',
    'dashboard.mechanic.active_job': 'Active Job',
    'dashboard.mechanic.completed': 'Completed',
    'dashboard.mechanic.rating': 'Rating',
    'dashboard.mechanic.current_job': 'Current Job',
    'dashboard.mechanic.btn_chat': 'Chat',
    'dashboard.mechanic.btn_phone': 'Phone',
    'dashboard.mechanic.btn_otw': 'OTW',
    'dashboard.mechanic.btn_arrived': 'Arrived & Start Work',
    'dashboard.mechanic.btn_done': 'Done',
    'dashboard.mechanic.analytics': 'EARNINGS ANALYTICS',
    'dashboard.mechanic.earnings_label': 'Total Earnings',
    'dashboard.mechanic.target_hit': 'Target Achieved',
    'dashboard.mechanic.performance': 'PERFORMANCE TRENDS',
    'dashboard.mechanic.recent_reviews': 'Recent Reviews',
    'dashboard.mechanic.no_reviews': 'No reviews yet.',
    'dashboard.mechanic.orders_in_title': 'INCOMING ORDERS',
    'dashboard.mechanic.btn_reject': 'Reject',
    'dashboard.mechanic.btn_accept': 'Accept',
    'dashboard.mechanic.no_orders': 'No incoming orders at the moment.',
    'mechanic.reg.title': 'PARTNER REGISTRATION',
    'mechanic.reg.subtitle': 'Start your future career at Oke Mekanik',
    'mechanic.reg.step1_title': 'Expertise Information',
    'mechanic.reg.speciality': 'Main Specialization',
    'mechanic.reg.spec_placeholder': 'Select Specialization',
    'mechanic.reg.spec_car': 'Passenger Car',
    'mechanic.reg.spec_motor': 'Motorcycle',
    'mechanic.reg.spec_truck': 'Heavy Vehicle / Truck',
    'mechanic.reg.spec_electric': 'Electric Vehicle',
    'mechanic.reg.experience': 'Work Experience (Years)',
    'mechanic.reg.exp_placeholder': 'Example: 5',
    'mechanic.reg.step2_title': 'Contact & Identity Information',
    'mechanic.reg.phone': 'Active Phone Number',
    'mechanic.reg.phone_placeholder': '0812...',
    'mechanic.reg.identity': 'ID Card / National ID Number',
    'mechanic.reg.id_placeholder': '3201...',
    'mechanic.reg.bio': 'Short Biography',
    'mechanic.reg.bio_placeholder': 'Tell us a bit about your expertise',
    'mechanic.reg.step3_title': 'Supporting Documents',
    'mechanic.reg.upload_ktp': 'UPLOAD ID CARD',
    'mechanic.reg.upload_cert': 'UPLOAD EXPERTISE CERTIFICATE',
    'mechanic.reg.step4_title': 'Confirmation & Agreement',
    'mechanic.reg.terms_text': '"By registering, I commit to maintaining Oke Mekanik\'s high quality standards, providing professional service, and upholding honesty in every job."',
    'mechanic.reg.terms_check': 'I agree to all terms, conditions, and the Oke Mekanik partner code of ethics.',
    'mechanic.reg.btn_back': 'BACK',
    'mechanic.reg.btn_next': 'NEXT',
    'mechanic.reg.btn_finish': 'FINISH',
    'mechanic.reg.processing': 'PROCESSING...',
    'mechanic.reg.secure_msg': 'Encrypted Data Security SSL/TLS',
    'payment.title': 'PAYMENT',
    'payment.secure_checkout': 'Secure Checkout',
    'payment.summary_title': 'SERVICE SUMMARY',
    'payment.label_problem': 'Problem',
    'payment.label_vehicle': 'Vehicle',
    'payment.label_order_id': 'Order ID',
    'payment.total_cost': 'TOTAL COST',
    'payment.methods_title': 'SELECT PAYMENT METHOD',
    'payment.methods_desc': 'Transactions are secure and encrypted using the Oke Mekanik system.',
    'payment.btn_pay': 'PAY NOW',
    'payment.processing': 'PROCESSING PAYMENT...',
    'payment.processing_desc': 'Please do not close this page until confirmation is complete.',
    'payment.success_title': 'SUCCESS!',
    'payment.success_desc': 'Thank you for trusting Oke Mekanik. Your vehicle is your future.',
    'payment.btn_dashboard': 'DASHBOARD',
    'payment.btn_invoice': 'DOWNLOAD OFFICIAL INVOICE (PDF)',
    'payment.error_not_found': 'BILLING DATA NOT FOUND',
    'payment.error_desc': 'Failed to load payment details for this order.',
    'forgot.title': 'FORGOT PASSWORD',
    'forgot.subtitle': 'Enter your email to receive reset instructions',
    'forgot.email': 'Email',
    'forgot.email_placeholder': 'email@example.com',
    'forgot.btn_send': 'SEND RESET LINK',
    'forgot.btn_back': 'BACK TO LOGIN',
    'forgot.success': 'Password reset instructions have been sent to your email',
    'hero.title.v27.part1': 'Future Workshop',
    'hero.title.v27.part2': 'in Your Hands.',
    'nav.login_mobile': 'Login',
    'common.id': 'ID',
    'common.en': 'EN'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
